# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: /
    weight: 10
  - name: Profesores
    url: profesores/
    weight: 20
